### PR TITLE
Defensive guard against elem's which aren't instance of Element

### PR DESCRIPTION
**Pull request by briangonzalez**

### CODE REVIEW

**Comment by briangonzalez** [comment]
@desandro 

A little primer: I've already contacted you about this issue, which I originally thought was related to matchesSelector, which we require through Flickity.

https://github.com/desandro/matches-selector/issues/6

Without this guard we were getting up to 500-1K exceptions per day. This little guard has caused the exceptions to subside and no reports of a suboptimal experience. Our implementation is a standard implementation, the only thing to note is that we're using Flickity in an Ember app.

**Comment by briangonzalez** [comment]
BTW, thanks for the awesome libraries.

**Comment by desandro** [comment]
I appreciate your contribution here, but I don't feel this is the right way to resolve this issue. Nearly all of the code I write expects to be run in a browser environment. Otherwise something will break. Rather than put in conditionals in the code, I'd prefer if the conditional happened elsewhere— don't run Isotope/Flickity/etc if its on the server.

I'm curious to learn what platform you are running that's triggering all these exceptions? React? If I can understand the issue better I hope to provide a better solution.

**Comment by briangonzalez** [comment]
The code _is only_ run in the browser. It's a clientside Ember app.

**Comment by desandro** [comment]
Any way you could provide a live demo or URL for me to take a look at? Is the problem that staticClick is being triggered automatically without an element?

**Comment by briangonzalez** [comment]
Yessir.

https://www.dollarshaveclub.com/blades

**Comment by briangonzalez** [comment]
Note, you won't see the stack trace our logs have captured.

**Comment by briangonzalez** [comment]
@desandro Following up here. Have you had a chance to poke around yet?

**Comment by desandro** [comment]
Thanks for the live URL! Looking at your code, I don't see anything crazy, but it's hard to figure out what is actually causing the issue.

Here's what I do know:  `matchesSelector` is used within `Flickity.prototype.getParentCell`, which is used in 2 places actually, `Flickity.prototype.staticClick`, and `LazyLoader.prototype.complete`. You're not using lazyLoad, so `staticClick` must be where the problem begins. Here's the [code in question, where getParentCell is used](https://github.com/metafizzy/flickity/blob/v1.2.1/js/drag.js#L320):

``` js
Flickity.prototype.staticClick = function( event, pointer ) {
  // get clickedCell, if cell was clicked
  var clickedCell = this.getParentCell( event.target );
  var cellElem = clickedCell && clickedCell.element;
  var cellIndex = clickedCell && utils.indexOf( this.cells, clickedCell );
  this.dispatchEvent( 'staticClick', event, [ pointer, cellElem, cellIndex ] );
};
```

Somehow, there is an `event` object with no `target`. Bingo.

Try adding this duck punch. You can add this to `face-web/mixins/sets-flickity`:

``` js
var _staticClick = Flickity.prototype.staticClick;
Flickity.prototype.staticClick = function( event ) {
  // bail if no target
  if ( !event || !event.target ) {
    // debugger here if you want to capture what's going on
    return;
  }
  // proceed
  _staticClick.apply( this, arguments );
};
```

**Comment by jakiestfu** [comment]
Shimming staticClick makes me nervous... Why wouldn't there be an event in some cases do you think, @desandro?

**Comment by briangonzalez** [comment]
@jakiestfu - this one does not scare me too much. what concerns you?

**Comment by desandro** [comment]
@jakiestfu I don't know what staticClick is triggered with out an `event.target`. But capturing when that happens should resolve this issue without ugly consequences.

**Comment by briangonzalez** [comment]
We're giving this a go. We'll let you know what happens.

**Pull request closed without merging**
